asso_maker_pass_secu:
    resource: "@AssoMakerPassSecuBundle/Controller/"
    type:     annotation
    prefix:   /

asso_maker_anim:
    resource: "@AssoMakerAnimBundle/Controller/"
    type:     annotation
    prefix:   /

asso_maker_sponso:
    resource: "@AssoMakerSponsoBundle/Controller/"
    type:     annotation
    prefix:   /

asso_maker_comptes_perso:
    resource: "@AssoMakerComptesPersoBundle/Controller/"
    type:     annotation
    prefix:   /

AssoMakerBaseBundle:
    resource: "@AssoMakerBaseBundle/Controller/"
    type:     annotation
    prefix:   /

AssoMakerPHPMBundle:
    resource: "@AssoMakerPHPMBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    pattern:   /logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

google_login:
    pattern: /login/check-google

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
