asso_maker_anim:
    resource: "@AssoMakerAnimBundle/Controller/"
    type:     annotation
    prefix:   /

asso_maker_sponso:
    resource: "@AssoMakerSponsoBundle/Controller/"
    type:     annotation
    prefix:   /

asso_maker_comptes_perso:
    resource: "@AssoMakerComptesPersoBundle/Controller/"
    type:     annotation
    prefix:   /

AssoMakerBaseBundle:
    resource: "@AssoMakerBaseBundle/Controller/"
    type:     annotation
    prefix:   /

AssoMakerPHPMBundle:
    resource: "@AssoMakerPHPMBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    pattern:   /logout

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
