security:
    encoders:
        PHPM\Bundle\Entity\User: plaintext


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        db:
            entity: { class: PHPMBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            provider: db
            http_basic:
                realm: "PHPLanningMaker"
            logout:
                path:   /logout
                invalidate_session: true
            anonymous:  ~
                
    access_control:
            - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/config/initiale, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/xxx.*, roles: ROLE_ADMIN }            
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
