security:
    encoders:
        AssoMaker\PHPMBundle\Entity\User: plaintext


    role_hierarchy:
        ROLE_USER:        ROLE_VISITOR
        ROLE_ORGA:        ROLE_USER
        ROLE_HARD:        ROLE_ORGA
        ROLE_ADMIN: [ROLE_USER, ROLE_VISITOR, ROLE_HARD]
        ROLE_HUMAIN:       [ROLE_ADMIN]
        ROLE_SOUSRESP:      [ROLE_ADMIN]
        ROLE_LOG:       [ROLE_HARD]
        ROLE_SECU:       [ROLE_HARD]
        ROLE_BUREAU:       [ROLE_SUPER_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_HUMAIN, ROLE_LOG, ROLE_SOUSRESP, ROLE_SECU, ROLE_HARD, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        #oauth.user_provider:
        #    id: oauth.user_provider


    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            oauth:
                resource_owners:
                  google: "/login/check-google"
                login_path: /login
                failure_path: /login
                default_target_path: /oauth/check
                oauth_user_provider:
                  service: oauth.user_provider
            logout: true
            anonymous: true

    access_control:
             - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
             - { path: ^/admin/, role: ROLE_ADMIN }
             - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
             - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
             - { path: ^/groupetache/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY}
             - { path: ^/tache/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY}
             - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
             - { path: ^/pass/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
             - { path: ^/comptesPerso/virement, roles: ROLE_VISITOR }
             - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
             - { path: ^/.*json, roles: IS_AUTHENTICATED_ANONYMOUSLY }
             - { path: ^/oauth, roles: ROLE_USER }
             - { path: ^/configv, roles: ROLE_SUPER_ADMIN }
             - { path: ^/configv/.*, roles: ROLE_SUPER_ADMIN }
             - { path: ^/analyse/.*, roles: ROLE_HARD }
             - { path: ^/.*, roles: ROLE_ORGA }
#             - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
jms_security_extra:
    secure_all_services: false
    expressions: true
