security:
    encoders:
        PHPM\Bundle\Entity\User: plaintext


    role_hierarchy:
        ROLE_USER:        ROLE_VISITOR
        ROLE_ADMIN:       [ROLE_USER, ROLE_VISITOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_VISITOR, ROLE_ALLOWED_TO_SWITCH]

    providers:
        db:
            entity: { class: PHPMBundle:Orga, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            provider: db
            form_login:
                login_path:  /login

            logout:
                path:   /logout
                invalidate_session: true
            anonymous:  ~
                
    access_control:
             - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
             - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
             - { path: ^/orga/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY}
             - { path: ^/groupetache/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY}
             - { path: ^/tache/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY}
             - { path: ^/autologin, roles: IS_AUTHENTICATED_ANONYMOUSLY}
             - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
             - { path: ^/config/initiale, roles: IS_AUTHENTICATED_ANONYMOUSLY }
             - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
             - { path: ^/.*json, roles: IS_AUTHENTICATED_ANONYMOUSLY }
             - { path: ^/.*, roles: ROLE_USER }               
#             - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
jms_security_extra:
    secure_all_services: false
    expressions: true
