parameters:
    my.validator.quartHeure.class:      PHPM\Bundle\Validator\QuartHeureValidator
    my.validator.inclus.class:      PHPM\Bundle\Validator\InclusValidator
    my.validator.debutAvantFin.class:      PHPM\Bundle\Validator\DebutAvantFinValidator
    my.validator.recoupe.class:      PHPM\Bundle\Validator\RecoupeValidator
    configController.class:      PHPM\Bundle\Controller\ConfigController

services:
    my.validator.quartHeure:
       class:      %my.validator.quartHeure.class%
       arguments: [@doctrine.orm.entity_manager]
       tags:
            - { name: validator.constraint_validator, alias: validator.quartHeure } 

    my.validator.inclus:
       class:      %my.validator.inclus.class%
       arguments: [@doctrine.orm.entity_manager]
       tags:
            - { name: validator.constraint_validator, alias: validator.inclus } 

    my.validator.debutAvantFin:
       class:      %my.validator.debutAvantFin.class%
       arguments: [@doctrine.orm.entity_manager]
       tags:
            - { name: validator.constraint_validator, alias: validator.debutAvantFin } 
            
    my.validator.plageHoraireRecoupe:
       class:      %my.validator.recoupe.class%
       arguments: [@doctrine.orm.entity_manager]
       tags:
            - { name: validator.constraint_validator, alias: validator.recoupe }
    configController:
       class:      %configController.class%
       arguments: []
      